import crypto, {BinaryLike} from 'crypto'

import encodeBase62 from './encodeBase62'

const SHORT_LINK_LENGTH = 8

const computeMD5 = (data: BinaryLike): Buffer =>
  crypto.createHash('md5').update(data).digest()
const buffer2Array = (buffer: Buffer): Array<number> => [...buffer]
const getRandomInt = (max: number): number =>
  Math.floor(Math.random() * Math.floor(max))

/**
 * Generates a string of length `SHORT_LINK_LENGTH`
 *
 * Short link is generated by computing a MD5 hash from a
 * concatenated string of UNIX timestamp and argument `shortLinkSeedData`.
 * Every byte of the computed hash is then encoded to base62.
 * First `SHORT_LINK_LENGTH` elements form such a string are returned.
 *
 * @param {string} shortLinkSeedData - If null function will use a random integer.
 * This number can be any number or string. For instance an IP address.
 */
export default async (shortLinkSeedData: string): Promise<string> => {
  return new Promise((resolve) => {
    setImmediate(() => {
      const additionalData = shortLinkSeedData || getRandomInt(1000)
      const timestamp = Date.now().toString()
      const toEncode = `${timestamp}${additionalData}`

      const hash = computeMD5(toEncode)

      const shortLink = buffer2Array(hash)
        .map((number) => encodeBase62(number))
        .join('')
        .slice(0, SHORT_LINK_LENGTH)

      return resolve(shortLink)
    })
  })
}
