'use strict'

const crypto = require('crypto')

const base62encoder = require('./base62encoder')

const SHORT_LINK_LENGTH = 8

const computeMD5 = (data) => crypto.createHash('md5').update(data).digest()
const buffer2Array = (buffer) => [...buffer]
const getRandomInt = (max) => Math.floor(Math.random() * Math.floor(max))

/**
 * Generates a string of length `SHORT_LINK_LENGTH`
 *
 * Short link is generated by computing a MD5 hash from a
 * concatenated string of UNIX timestamp and argument `shortLinkSeedData`.
 * Every byte of the computed hash is then encoded to base62.
 * First `SHORT_LINK_LENGTH` elements form such a string are returned.
 *
 * @param {string} shortLinkSeedData - If null function will use a random integer.
 * This number can be any number or string. For instance an IP address.
 */
const generateShortLink = async (shortLinkSeedData) => {
  return new Promise((resolve, reject) => {
    setImmediate(() => {
      const additionalData = shortLinkSeedData || getRandomInt(1000)
      const timestamp = Date.now().toString()
      const toEncode = `${timestamp}${additionalData}`

      const hash = computeMD5(toEncode)

      let shortLink = buffer2Array(hash)
        .map((number) => base62encoder.encode(number))
        .join('')

      resolve(shortLink.slice(0, SHORT_LINK_LENGTH))
    })
  })
}

module.exports = {
  generateShortLink,
}
